### ISSUE TITLE
interpretation of label and haslabel lists

### ISSUE THREAD

**Issue by iagogv3** [JanMarvin/readspss#17]
Dear Jan,

Thank you very much for the package! I founded to it since I had to work with a `*.sav` with password, and no other R package I know (`haven`, `foreign, etc.) seem to have this option.

The purpose of this issue is asking for a bit more of documentation on the values of the object returned by `read.sav`, since, for example, I cannot understand the values under the `varmatrix` attribute.

But I am intrigued since the data.frame I opened has 219 variables, while the attribute `label` is a list of length 183, as the attribute `haslabel`. I would like to know to which variable correspond each of the labels, so I tried to look at `haslabel`, but the components of the list arrive to `309`, so they are not the indices of the variables in the data.frame, as I expected. How can I decipher this problem?

Thank you again!

**Comment by JanMarvin** [comment]
Hi @iago-pssjd,

glad that you find the package useful. I'll see if I can explain some of the values.

The returned attribute `label` corresponds to value labels e.g.  something like y = yes, n = no. The information which variable the label corresponds with is recorded in attribute `haslabel`. If I remember correctly a label value might be used multiple times, e.g. something like yes and no might be used multiple times in a questionnaire dataset. See:

```{r}
fl <- system.file("extdata", "electric.sav", package = "readspss")

# import without labels
dd <- read.spss(fl, convert.factors = F)
# vs import with labels
dd <- read.spss(fl, convert.factors = T)
```

The attribute `varmatrix` corresponds to some SPSS internals. 
https://github.com/JanMarvin/readspss/blob/880acfe8614a85d0480202b201522f632ded316e/src/readsav.cpp#L240-L254

* `vtyp` is 0 for numerics and 1 for characters (and -1 for long strings, but this is not returned). 
* vflag corresponds to `var.labels` e.g. if a variable is labeled. Regarding your Question, I have found that the SPSS sav files may contain unused information. It might well be possible that your file contains labels for variables no longer available in the data.
* `nmiss` corresponds to missing variables information (is it a single missing value or multiple values or even a range of missing values)
* the others are of no importance for R

Handling of the value position and labels is provided by the package using `convert.factors = TRUE`. Again, if I'm not mistaken there is a possibility of long labels, which are stored differently in the sav file (which has seen numerous iterations over time).

Let me know if this answers your question.

**Comment by iagogv3** [comment]
Thank you! @JanMarvin ,

Indeed you answer my question. I see in the example you provide that `haslabel` values correspond to indices of variables with value labels. 

The strange is why in my dataset this is not the case. It could be, as you say, that SPSS file contain unused information, since for example, the second element of the attribute `label` seems to give the labels of the variable 19, but the second element of `haslabel` is 43, and as tould you before, the last value of `haslabel` is 309, but the dataset has only 219 variables.

There would be some way to identify these variables? Or may the dataset be misconfigured in such a way that `haslabel` indices would not correspond any more to the actual variables they should? Unfortunately, the dataset I am working has confidential data so I cannot share it.

Thank you!

**Comment by JanMarvin** [comment]
there really is no way to tell to which missing variables the labels correspond to. if you fear that the labels are arranged incorrectly the only solution would be to open the file in spss (or maybe pspp) I'm afraid.
also keep in mind that not every variable must contain a label. in sav files the label list and the variable list are disjunct. your file might be completely valid, just maybe incomplete regarding certain maybe confidential information or variables used for construction of other variables. the only theoretical issue I can come up with would be the existence of long strings in which case the counting might be off. I cannot remember from the top of my head if such cases are handled correctly.

I'll close this issue as the matter seems resolved on my end. feel free to reopen if something new comes up.
