### ISSUE TITLE
Missing variable labels in read.sav?

### ISSUE THREAD

**Issue by iembry** [JanMarvin/readspss#19]
Greetings. In the description of the returned data.frame objects in read.sav, the following are defined:

`val.label` = value labels

`var.label` = variable labels

Within the actual R code, the following exists:

`val.labels <- attribs$vallabels` # line 155

`attr(data, "var.label") <- val.labels` # line 514

Shouldn't var.label (variable labels) be a different attribute than val.label (value labels)?

Thank you in advance.

**Comment by JanMarvin** [comment]
Hi @iembry , thanks for the issue. It might be just a wording issue, but I'll look into it

**Comment by JanMarvin** [comment]
I've updated the documentation and removed the entry to val.label. The code and documentation might not be entirely consistent  (I've worked on this with larger breaks in between), but nothing is lost and everything apart from the documentation looks correct. If you want to further improve this, pull requests on code or documentation are always welcome.

**Comment by iembry** [comment]
@JanMarvin Thank you for making the changes to the documentation. I appreciate that.
