### ISSUE TITLE
read.sav never finishes

### ISSUE THREAD

**Issue by guidohooiveld** [JanMarvin/readspss#26]
Hi,
Thanks for developing `readspss`!

I use it once in a while to import SPSS files from collaborators into R.
Last time (couple of months ago) I used it, everything worked fine. However, today I would like to import a file, but now R hangs for hours... Could you please have a look?

What did i do?

I installed (the latest version of) `readspss` through:
`remotes::install_github("JanMarvin/readspss")`

R hangs also when reading the included sample file. In other words; the code below ran for > 30 minutes without completing, and then I killed R...

```
> library(readspss)
> 
> fls <- system.file("extdata", "electric.sav", package="readspss")
> fls
[1] "C:/Program Files/R/R-4.2.1/library/readspss/extdata/electric.sav"
> 
> df_s <- read.sav(fls) # had to kill R session after 30 mins
```

```
> sessionInfo()
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] LC_COLLATE=English_United States.utf8 
[2] LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] readspss_0.16.1

loaded via a namespace (and not attached):
[1] compiler_4.2.1 tools_4.2.1    Rcpp_1.0.9    
> 
```

**Comment by JanMarvin** [comment]
Hi @guidohooiveld , it might be that you have to reinstall Rcpp and BH? I triggered a rebuild, this will run the tests, but I don't expect an error.

**Comment by JanMarvin** [comment]
Just as reference, it works locally and in all CI environments

``` r
library(readspss)
fl <- system.file("extdata", "electric.sav", package = "readspss")
head(read.sav(fl))
#>   CASEID      FIRSTCHD AGE DBP58 EDUYR CHOL58 CGT58 HT58 WT58  DAYOFWK VITAL10
#> 1     13    NONFATALMI  40    70    16    321     0 68.8  190     <NA>   ALIVE
#> 2     30    NONFATALMI  49    87    11    246    60 72.2  204 THURSDAY   ALIVE
#> 3     53 SUDDEN  DEATH  43    89    12    262     0 69.0  162 SATURDAY    DEAD
#> 4     84    NONFATALMI  50   105     8    275    15 62.5  152 WEDNSDAY   ALIVE
#> 5     89 SUDDEN  DEATH  43   110    NA    301    25 68.0  148   MONDAY    DEAD
#> 6    102    NONFATALMI  50    88     8    261    30 68.0  142   SUNDAY    DEAD
#>   FAMHXCVR CHD
#> 1      YES   1
#> 2       NO   1
#> 3       NO   1
#> 4      YES   1
#> 5       NO   1
#> 6       NO   1
```

**Comment by guidohooiveld** [comment]
Thanks for your prompt reply!

Per your suggestion I reinstalled the packages `Rcpp` and `BH`, followed by a reinstall of `readspss`. Unfortunately that did not solve the problem...

```
library(readspss)
fl <- system.file("extdata", "electric.sav", package = "readspss")
head(read.sav(fl))
```

It still hangs for > 30 mins... utilizing max CPU (= 1 core) for R, and a large but fluctuating amount of memory (varying between 0.3 and 4 GB... in screenshot it is 2.5 GB). So R is doing something, but R-gui is not responsive anymore, so I had to kill it through Windows task manager.


![screenshot](https://user-images.githubusercontent.com/22979991/193948439-a2ef32f0-418c-4c64-b1ce-211a6715b7ba.png)

**Comment by JanMarvin** [comment]
Hm that's odd. It works with Windows, Linux and Mac (Intel and M1) and it works in an instance without that much memory consumption. Just to limit the things that might occur in between, could you install from r-universe?
``` r
  # Enable repository from janmarvin
  options(repos = c(
  janmarvin = 'https://janmarvin.r-universe.dev',
  CRAN = 'https://cloud.r-project.org'))
  # Download and install readspss in R
  install.packages('readspss')
```

This are binaries built and tested on GitHubs CI. Other than that I'm a bit clueless too.

If that still does not help, you could run read.sav with `debug=TRUE` to see if readspss is working at all and it might tell us where it hangs. After all there might be something that derails readspss. And you should stop R as soon as it stops responding.

**Comment by guidohooiveld** [comment]
Thanks for all your suggestions!

I installed `readspss` from r-universe, and then tried again. I left my R-session unattended, and continued with other work. I kept regularly checking the R-session, and at a certain moment it turned out the sample file was imported,... but it took long time (approx 45 mins, see below).

So... it works, but very slowly. FWIW: during my checking I noticed that the 'printing' of the first part of the info (the lines starting with rtype2) took long time to complete.

To rule out something is wrong with the sample file, I imported it through the library `foreign`. That worked flawlessly. 

Do you have any further ideas/suggestions/things I can check? Since it apparently is specific to my PC, I am also clueless...

  
```
> Sys.time()
[1] "2022-10-05 09:15:41 CEST"
> 
> library(readspss)
> fl <- system.file("extdata", "electric.sav", package = "readspss")
> head( read.sav(fl, debug=TRUE) )
Datalabel:SPSS DATA FILE MS WINDOWS Release 6.1
swapit: 0
K: 13 
N: 240 
rtype: 2
rtype 2 CASEID nmistype 0 vflag 1
rtype 2 FIRSTCHD nmistype 0 vflag 1
rtype 2 AGE nmistype 0 vflag 1
rtype 2 DBP58 nmistype 0 vflag 1
rtype 2 EDUYR nmistype 0 vflag 1
rtype 2 CHOL58 nmistype 0 vflag 1
rtype 2 CGT58 nmistype 0 vflag 1
rtype 2 HT58 nmistype 0 vflag 1
rtype 2 WT58 nmistype 0 vflag 1
rtype 2 DAYOFWK nmistype 1 vflag 1
rtype 2 VITAL10 nmistype 0 vflag 1
rtype 2 FAMHXCVR nmistype 0 vflag 1
rtype 2 CHD nmistype 0 vflag 1
rtype 3 rtype 4 rtype 3 rtype 4 rtype 3 rtype 4 rtype 3 rtype 4 rtype 7 rtype 7; subtyp 3; size 4; count 8
rtype 7 rtype 7; subtyp 4; size 8; count 3

sysmiss -179769313486231570838400602864442228000008602082842266064064680402680408280648240046204888888288080622822420842246006644866884860462806420066668022046626024066662068886808602862886866800048228686262462640668044406484606206082824406288200264266406808068464046840608044222802268424008466606886862062820068082688.000000l
highest -1
lowest -2

-- end of header
"CASEID" "FIRSTCHD" "AGE" "DBP58" "EDUYR" "CHOL58" "CGT58" "HT58" "WT58" "DAYOFWK" "VITAL10" "FAMHXCVR" "CHD"
0 0 0 0 0 0 0 0 0 0 0 1 0
0 0 0 0 0 0 0 0 0 0 0 1 0
-- Start: Data Part 
cflag: 1
curpos: -1791007600
endpos: -1791007600
val_b: 13
val_b: 3
val_b: 40
val_b: 70
val_b: 16
321.000000 
val_b: 0
68.800000 
190.000000 
val_b: 9
val_b: 0
Y
val_b: 1
val_b: 30
val_b: 3
val_b: 49
val_b: 87
val_b: 11
246.000000 
val_b: 60
72.200000 
204.000000 
val_b: 5
val_b: 0
N
val_b: 1

<< snip >>

N
val_b: 0
155.000000 
val_b: 1
val_b: 47
val_b: 83
206.000000 
val_b: 0
val_b: 66
185.000000 
val_b: 9
val_b: 0
N
val_b: 0
stop: eof
-- End: Data Part 
  CASEID      FIRSTCHD AGE DBP58 EDUYR CHOL58 CGT58 HT58 WT58  DAYOFWK
1     13    NONFATALMI  40    70    16    321     0 68.8  190     <NA>
2     30    NONFATALMI  49    87    11    246    60 72.2  204 THURSDAY
3     53 SUDDEN  DEATH  43    89    12    262     0 69.0  162 SATURDAY
4     84    NONFATALMI  50   105     8    275    15 62.5  152 WEDNSDAY
5     89 SUDDEN  DEATH  43   110    NA    301    25 68.0  148   MONDAY
6    102    NONFATALMI  50    88     8    261    30 68.0  142   SUNDAY
  VITAL10 FAMHXCVR CHD
1   ALIVE      YES   1
2   ALIVE       NO   1
3    DEAD       NO   1
4   ALIVE      YES   1
5    DEAD       NO   1
6    DEAD       NO   1
> 
> Sys.time()
[1] "2022-10-05 09:49:36 CEST"
> 
```



For comparison: import through` foreign`:
```
> Sys.time()
[1] "2022-10-05 10:17:06 CEST"
> 
> library(foreign)
> fl <- system.file("extdata", "electric.sav", package = "readspss")
> head( read.spss(file=fl, to.data.frame=TRUE) )
  CASEID      FIRSTCHD AGE DBP58 EDUYR CHOL58 CGT58 HT58 WT58  DAYOFWK
1     13    NONFATALMI  40    70    16    321     0 68.8  190     <NA>
2     30    NONFATALMI  49    87    11    246    60 72.2  204 THURSDAY
3     53 SUDDEN  DEATH  43    89    12    262     0 69.0  162 SATURDAY
4     84    NONFATALMI  50   105     8    275    15 62.5  152 WEDNSDAY
5     89 SUDDEN  DEATH  43   110    NA    301    25 68.0  148   MONDAY
6    102    NONFATALMI  50    88     8    261    30 68.0  142   SUNDAY
  VITAL10 FAMHXCVR CHD
1   ALIVE      YES   1
2   ALIVE       NO   1
3    DEAD       NO   1
4   ALIVE      YES   1
5    DEAD       NO   1
6    DEAD       NO   1
> 
> Sys.time()
[1] "2022-10-05 10:17:06 CEST"
>
```

**Comment by JanMarvin** [comment]
At the moment I'm a bit clueless to be honest. It could have been related to some compiler option, but that should be ruled out now that we've tried two different installations and it looks like you're on a basic Win10 system.

One more thing to test, could you check if it works via command line? Maybe Rgui is interfering? All my tests are  via command line or in RStudio. Though my RGui works as well.

**Comment by JanMarvin** [comment]
Your R librarys folder isn't by chance on a netshare and you are behind a terribly slow internet connection?

I can look into it a bit more, but for me it's as quick as foreign. Did a Microbenchmark (times = 100) and readspss takes 6.8ms while foreign takes 1.9ms on the example file. And memory consumption is ~700mb for RStudio running the benchmark (and nearly all of the 700mb are only RStudio).

**Comment by guidohooiveld** [comment]
Thanks for following up on this, despite the issue being very unusual and likely being specific for my setup... 

Regarding your questions:
No, the R-library folder is on the local c-drive, with full read/write access.
No, I am connected through my university network which is very fast.

Anyway, one more observation: I realized that I still had older version of R (R-4.0.3 ) with `readspss` installed. When running the exact lines of code it worked very fast! Obviously I don't dare to update `readspss` in that version of R....

For now I will revert to the old version of `R`/`readspss` to import SPSS files.
Again, I realize that my problem is not reproducible at your site, which makes debugging very difficult/impossible. Yet, please let me know if you would like me to check some more things. I also understand if you decide to close this issue.

Regardless your decision: I would like to thank you again for you prompt responses!

```
> Sys.time()
[1] "2022-10-05 13:32:25 CEST"
> 
> library(readspss)
> fl <- system.file("extdata", "electric.sav", package = "readspss")
> head( read.sav(fl, debug=FALSE) )
  CASEID      FIRSTCHD AGE DBP58 EDUYR CHOL58 CGT58 HT58 WT58  DAYOFWK VITAL10
1     13    NONFATALMI  40    70    16    321     0 68.8  190     <NA>   ALIVE
2     30    NONFATALMI  49    87    11    246    60 72.2  204 THURSDAY   ALIVE
3     53 SUDDEN  DEATH  43    89    12    262     0 69.0  162 SATURDAY    DEAD
4     84    NONFATALMI  50   105     8    275    15 62.5  152 WEDNSDAY   ALIVE
5     89 SUDDEN  DEATH  43   110    NA    301    25 68.0  148   MONDAY    DEAD
6    102    NONFATALMI  50    88     8    261    30 68.0  142   SUNDAY    DEAD
  FAMHXCVR CHD
1      YES   1
2       NO   1
3       NO   1
4      YES   1
5       NO   1
6       NO   1
> 
> Sys.time()
[1] "2022-10-05 13:32:25 CEST"
> 
> 
> 
> sessionInfo()
R version 4.0.3 Patched (2020-12-21 r79668)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] readspss_0.14

loaded via a namespace (and not attached):
[1] compiler_4.0.3 tools_4.0.3    Rcpp_1.0.8.3  
> 
```

**Comment by guidohooiveld** [comment]
BTW, forgot to add: when using the current versions of R and R-studio, R-studio crashes when running it in command line. "R encountered a fatal error". I saw quickly a notification regarding something with java, if I recall correctly (couldn't make a screenshot of that), but I don't know whether this is relevant to mention.


![Rstudio](https://user-images.githubusercontent.com/22979991/194053056-34f88bfb-4275-46cf-9548-08e12fc5b4f5.png)

**Comment by JanMarvin** [comment]
It might be required to install R completely. Not sure what's going on, but I'm sure that crashing is not the expected behavior of Rstudio :)

Other than that I'm not sure what exactly happens. You could check readspss with the R command line (something like CMD and the path to C:/.../R/bin/R.exe) to check if you R installation is causing the lag. I have a Windows installation at home I can check later this week.

Being helpful towards users should be part of the job description of open source developers. Glad that you find the program useful nevertheless.

**Comment by guidohooiveld** [comment]
I agree, such crash is not expected at all!

I ran R through the command line (cmd; `R.exe`) in vain; same slow behavior as reported. Also reinstalling R-4.2.1 did not help...

Will also check another Windows machine tomorrow (ask colleague), and report back.

**Comment by guidohooiveld** [comment]
Update: I checked on another machine (laptop colleague), and unfortunately experienced the same, long run time...

`SessionInfo()` of R on that laptop:

```
> sessionInfo()
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8 
[2] LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] readspss_0.16.1

loaded via a namespace (and not attached):
[1] compiler_4.2.1 tools_4.2.1    Rcpp_1.0.9    
>


```

**Comment by JanMarvin** [comment]
Thanks, really strange. Long shot, but maybe it's caused by your university antivirus software? The time measurements above are from my windows 10 at work and I've never experienced something similar when developing the package.

Could you check if the `readstata13` (on CRAN) or `readsas` (GitHub only) examples are slow as well? I'm the author of both and they share the same logic for file loading.

**Comment by guidohooiveld** [comment]
Update:
the `readstata13` and `readsas` examples work fine (= instantly).

I also talked to our IT department. All computer are protected with centrally managed Windows Defender Advanced Threat Protection with all kinds of bells and whistles. I don't know more details, but upon my request they excluded the R-installation folder from scanning (`C:\Program Files\R\R-4.2.1)`. Unfortunately that did not have any impact. :(

Looks like there are no options left other than leave it here... Doesn't feel satisfactory, but since it is not reproducible at your side, this seems the most logical thing to do?

**Comment by JanMarvin** [comment]
Thanks, you're really going the extra mile. I'll have a look this weekend/maybe later tonight. I have Windows 10 at home as well. Maybe something catches my eye.

**Comment by JanMarvin** [comment]
Did you observe a specific section in the debug output where readspss hangs? You mention that the rtype 2 part is slow, anything specific? This could point me to possible bugs in my code.

Something like:
* lines 1:5 instantly
* lines 6:20 slow and memory starts to grow?

**Comment by guidohooiveld** [comment]
Nice that you still would like to give some follow-up on this.

Line 1 is printed instantly: `Datalabel:SPSS DATA FILE MS WINDOWS Release 6.1`.

Then, after approximately 12 minutes  Line 2 (`swapit: 0`) to Line 6 (`rtype 2 CASEID nmistype 0 vflag 1`) are printed. 

Please note, it could be that more lines are printed, maybe even all lines starting with `rtype 2`, but since I could not scroll down in the R-gui window (because R behaves as 'frozen'), I could not see those lines. Yet I noticed that very likely more was printed after line 6.

Finally, after approximately 25 more minutes `read.sav` finishes, showing all output.

I am sure you will know this, but within the function `read.sav` this is the line that takes such long time to finish (it is the actual call to Rccp). I used `debug(read.sav)`.
```
Browse[2]> 
debug: data <- readsav(filepath, debug, encStr, ownEnc)
```

**Comment by JanMarvin** [comment]
Alright, I'm able to reproduce the issue. With Windows 10 R 4.2.1, latest Rtools and RGui. Looks like it is UCRT related.

**Comment by JanMarvin** [comment]
Okay, I have a pull request that fixes things for me at #27 . Would be  glad if you could double check @guidohooiveld . You should be able to install this with `remotes::install_github("JanMarvin/readspss", ref = "boost_regex")`.

For some reason `std::regex` is crashing R. To be honest, I have no clue why this happens. Might be a bug in Rtools, but I was not in the mood to figure this out. R on Windows is a black box to me and I'm glad that there are more patient people than me who care about the R windows port. Since my work Windows is still 4.1, I guess this was not triggered. Therefore you might have been the first to try it on Windows 4.2.

Anyhow, the fix for me was to replace `std::regex` with `boost::regex` which should be the entirely same thing (the code might actually be from the same author). The other fix would have been to increase the C++ version in the hopes that it would be supported in C++14 (which is the default in R 4.x I believe). But that would break builds on older R 3.6. Still I'm a clueless why this works on the CI and worked in Windows for R 4.1. But if this works just as well on all OSes, I will merge the PR.

**Comment by JanMarvin** [comment]
Looks like this issue: https://github.com/tesseract-ocr/tesseract/issues/3830

**Comment by guidohooiveld** [comment]
YES! After installing the fix, the example file is processed instantly!
Thanks a lot for fixing this.

```
> Sys.time()
[1] "2022-10-10 09:02:21 CEST"
> library(readspss)
> fl <- system.file("extdata", "electric.sav", package = "readspss")
> head( read.sav(fl, debug=FALSE) )
  CASEID      FIRSTCHD AGE DBP58 EDUYR CHOL58 CGT58 HT58 WT58  DAYOFWK
1     13    NONFATALMI  40    70    16    321     0 68.8  190     <NA>
2     30    NONFATALMI  49    87    11    246    60 72.2  204 THURSDAY
3     53 SUDDEN  DEATH  43    89    12    262     0 69.0  162 SATURDAY
4     84    NONFATALMI  50   105     8    275    15 62.5  152 WEDNSDAY
5     89 SUDDEN  DEATH  43   110    NA    301    25 68.0  148   MONDAY
6    102    NONFATALMI  50    88     8    261    30 68.0  142   SUNDAY
  VITAL10 FAMHXCVR CHD
1   ALIVE      YES   1
2   ALIVE       NO   1
3    DEAD       NO   1
4   ALIVE      YES   1
5    DEAD       NO   1
6    DEAD       NO   1
> Sys.time()
[1] "2022-10-10 09:02:21 CEST"
>
``` 


```
> 
> sessionInfo()
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] LC_COLLATE=English_United States.utf8 
[2] LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] readspss_0.16.1

loaded via a namespace (and not attached):
[1] compiler_4.2.1 tools_4.2.1    Rcpp_1.0.9    
> 

```

**Comment by JanMarvin** [comment]
Thank you for being persistent :)
The PR is merged with main and I'll bump the version later this week. Will run a few extra checks on non public files first.
